# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 自动采集

# 触发条件
on:
  # push的时候触发
  # push:
  #   branches: main
  workflow_dispatch:
  # 定时触发
  schedule:
    - cron: '0 0 1 */6 *'
    # 表达式生成  https://crontab.guru/
    # 此处是UTC时间 即北京时间 -8小时
#     - cron: '40 2,12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install/payzbar
      run: |
        sudo apt-get install libzbar0
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - uses: browser-actions/setup-chrome@latest
    - name: Setup Chrome
      run: chrome --version
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version
    - name: 执行任务
      env:
        FM_PASSWORD: ${{ secrets.FM_PASSWORD }}
        FM_USERNAME: ${{ secrets.FM_USERNAME }}
      run: |
        python getGithub.py
        python test.py
    # - name: 推送更改
    #   uses:  ad-m/github-push-action@master
    #   with:
    #      branch: master
